version: 2
models:
  - name: dim_people
    columns:
      - name: peopleid
        description: Primary key of the people table
        tests:
          - unique
          - not_null
      - name: fullname
        description: The full name.
    description: ""
  - name: fact_logins
    description: One record per login.
    columns:
      - name: loginid
        description: Primary key of the login.
        tests:
          - unique
          - not_null
      - name: logintimestamp
        description: "When the user logged in. "
      - name: dayofweek
        description: Number indicating the dayOfWeek. 1 = Monday.
      - name: peopleid
        description: Foreign key for peopleId. Should be renamed in public schema.
        tests:
          - not_null
          - relationships:
              to: ref('dim_people')
              field: peopleid
      - name: fullname
        description: Full name of people
